name: Upload Images to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - 'games/'

env:
    DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
    push_minecraft_latest:
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        - name: Docker login
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - name: Build and push Docker Images
          id: docker_build
          uses: docker/build-push-action@v2.5.0
          with:
            push: true
            context: games/minecraft/
            tags: casteloig/mine-server:latest

    push_factorio_latest:
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        - name: Docker login
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - name: Build and push Docker Images
          id: docker_build
          uses: docker/build-push-action@v2.5.0
          with:
            push: true
            context: games/factorio/
            tags: casteloig/factorio:latest
