name: Upload binary to new release

on:
  release:
    types: [published]

env:
    DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
    upload_binary:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}

        - name: Build
          uses: actions/setup-go@v2
          with:
            go-version: '1.17' # The Go version to download (if necessary) and use.
        - run: go build -mod vendor -o ./bin/cuack-ctl ./cmd/cuack-ctl/

        - name: upload linux artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./bin/cuack-ctl
            asset_name: cuack-ctl
            asset_content_type: application/octet-stream

    push_cuack_image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        - uses: actions/setup-go@v2
          with:
            go-version: '1.9.3' # The Go version to download (if necessary) and use.
        - run: go build -o ./bin/cuack-ctl ./cmd/cuack-ctl/  
        - name: Docker login
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - name: Build and push Docker Images
          id: docker_build
          uses: docker/build-push-action@v2.5.0
          with:
            push: true
            context: .
            tags: casteloig/cuack:latest