name: Release cuack

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
    release_demo_cuack:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          #goos: [linux, windows]
          #goarch: ["386", "amd64"]
          goos: [linux]
          goarch: [amd64]
      if: github.event_name == 'push'
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}

        - name: Build
          uses: actions/setup-go@v2
          with:
            go-version: '1.17' # The Go version to download (if necessary) and use.
        - run: go build -mod vendor -o ./bin/cuack-ctl ./cmd/cuack-ctl/

        - name: Release
          if: startsWith(github.ref, 'refs/tags/v')
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            make release

        - name: Upload release artifacts
          if: startsWith(github.ref, 'refs/tags/v')
          uses: actions/upload-artifact@v2
          with:
            name: release-artifacts
            path: |
              ./bin/cuack-ctl

