name: Upload Images to DockerHub

on:
  push:
    branches:
      - main
    tags:
      - latest

jobs:
    release_demo_cuack:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux, windows]
          goarch: ["386", "amd64"]
      if: github.event_name == 'push'
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN_GITHUB }}

        - name: build bin
          uses: actions/setup-go@v2
          with:
            go-version: '1.17' # The Go version to download (if necessary) and use.
        - run: go build -mod vendor -o ./bin/cuack-ctl ./cmd/cuack-ctl/

        - name: release  
          uses: wangyoucao577/go-release-action@v1.17
          with:
            github_token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            goversion: "https://dl.google.com/go/go1.17.linux-amd64.tar.gz"
            project_path: "./bin"
            binary_name: "cuack-ctl"